### ISSUE TITLE
Use global range for term value

### ISSUE THREAD

**Issue by Francesko90** [nationaldronesau/FlirImageExtractor#1]
Hi 

Congratulations for this library, I use it to convert my flir image fff to jpg
Is it possible use a range of global value instead of use min,max data get from file?

I need to process more flir data captured in different day

Many thanks

**Comment by aidankinzett** [comment]
Just to check this is for converting multiple images so that they can be easily compared? I should be able to easily add this feature

**Comment by Francesko90** [comment]
This is it for convert multiple image using same parameters, for example I have two images:
 - Image 1: Min: 20° Max:70°
 - Image 2: Min: 25° Max: 80° 

The result images have same RGB color for different temperature. 
If I could set same min and max the resulting images have same color for same temperatur.
I think that a overload of safe method with extra paramaters (min,mix) can be enough: https://github.com/nationaldronesau/FlirImageExtractor/blob/master/flirimageextractor/__init__.py#L253

**Comment by aidankinzett** [comment]
I've added the optional parameters to the save images function. The only issue with this is that you need to know the min and max of all photos before saving any of them. I might look at adding an option to input an array of images and the maximum and minimum values from the array will be used instead of manually specifying them

**Comment by Francesko90** [comment]
> The only issue with this is that you need to know the min and max of all photos before saving any of them

Yes, my idea is to use global value for all dataset i.e (-20,+200)

>  I might look at adding an option to input an array of images and the maximum and minimum values from the array will be used instead of manually specifying them

Nice idea!

**Comment by Francesko90** [comment]
I tested new version, following result of processing:

Min: 0 Max: 200

![0-200](https://user-images.githubusercontent.com/6740590/66203062-a2658580-e6a7-11e9-92ae-5c2180dd0e67.jpg)

Min: -10 Max: 200
![ph001308](https://user-images.githubusercontent.com/6740590/66203124-ce810680-e6a7-11e9-8937-1c4f95330da4.jpg)

Min: -10 Max: -5

![ph001308](https://user-images.githubusercontent.com/6740590/66203154-e9ec1180-e6a7-11e9-96e9-563975e5c8b3.jpg)

**Comment by aidankinzett** [comment]
Looks like I wasn't using brackets properly for the temperature normalisation, I've pushed a patch which should fix it, let me know how it goes
