### ISSUE TITLE
using FlirImageExtractor with Pydroid. ExifTool as itself cannot be installed

### ISSUE THREAD

**Issue by EduardoAlbaizar** [nationaldronesau/FlirImageExtractor#29]
I would like to use FlirImageExtractor but despite there is an exiftool app for android, the script looks for the executable in path folders as if it was run in windows.
This is the simple script i would like to get running before going further improving the script in my computer.

I would truly appreciate if someone could provide any useful tip. Best regards

import flirimageextractor
from glob import glob
import os

flir = flirimageextractor.FlirImageExtractor()
files = glob("C:/FLIR/*.JPG")
files = [texto.replace("\\", "/") for texto in files]
files = [os.path.basename(file) for file in files]
for file in files:
    try:
        flir.process_image('FLIR/'+file)
        flir.save_images()
        thermal=flir.get_thermal_np()
        flir.plot()
    except Exception as e:
        print(f"Error al procesar el archivo {file}: {e}")

**Comment by williams9438** [comment]
def test2():
    files = glob(f"{base_dir}/*.jpg")
    files = [texto.replace("\\", "/") for texto in files]
    files = [os.path.basename(file) for file in files]
    for file in files:
        print(file)
        try:
            flir.process_image(f"{base_dir}/{file}")
            flir.save_images()
            thermal=flir.get_thermal_np()
            flir.plot()
        except Exception as e:
            print(f"Error al procesar el archivo {file}: {e}")
    

test
