### ISSUE TITLE
Flir Lepton

### ISSUE THREAD

**Issue by IeiuniumLux** [nationaldronesau/FlirImageExtractor#4]
Can this version of the library work with the [Flir Lepton 3.5](https://www.flir.com/products/lepton/)?

**Comment by aidankinzett** [comment]
I don't have any images from the camera to test it with, if you send one through I could test it for you

**Comment by IeiuniumLux** [comment]
Here you go, thanks!

![filname_1](https://user-images.githubusercontent.com/3729432/74793102-39586600-5274-11ea-82c4-1f8993be48e8.jpg)

**Comment by aidankinzett** [comment]
It looks like that image doesnt contain any of the original metadata, do you have the original image off of the camera?

**Comment by Species919** [comment]
Was this ever solved?

**Comment by williams9438** [comment]
> Was this ever solved?

No image was provided for testing. closing now
