### ISSUE TITLE
filenames containing '.' are not parsed properly

### ISSUE THREAD

**Issue by vasarhelyi** [nationaldronesau/FlirImageExtractor#7]
Please change this line

thermal_output_filename_array = self.flir_img_filename.split(".")

to e.g. this:

thermal_output_filename_array = os.path.splitext(self.flir_img_filename)

to handle dots in filenames properly. Thanks!

**Comment by vasarhelyi** [comment]
Sorry, there are two lines that should be changed like this:

**Comment by vasarhelyi** [comment]
... and the splitext keeps the '.' in the second half so adding that again to the filenames is also not necessary any more... sorry, would have been better to include a patch...

**Comment by williams9438** [comment]
Thanks for the recommendation.
Added in v1.5.6
