### ISSUE TITLE
Image captured by PureThermal 2 - FLIR Lepton

### ISSUE THREAD

**Issue by Varat7v2** [nationaldronesau/FlirImageExtractor#9]
I captured image from Pure Thermal - FLIR Lepton camera, but its not working with FlirImageExtractor. Its throwing the following error: 
`KeyError: 'RawThermalImageType'` And when I run exiftool <flir_image>, lots of meta-data are missing? How should I do to capture image with full image meta-data details?
Any kind of suggestions / references will be helpful to me.

When I run exiftool `<on-my-image>`, its just showing the following data:

> ExifTool Version Number : 10.80
File Name : my_photo-1.jpg
Directory : .
File Size : 5.7 kB
File Modification Date/Time : 2020:05:04 20:28:10+05:30
File Access Date/Time : 2020:05:04 20:28:47+05:30
File Inode Change Date/Time : 2020:05:04 20:28:10+05:30
File Permissions : rw-rw-r--
File Type : JPEG
File Type Extension : jpg
MIME Type : image/jpeg
JFIF Version : 1.02
Resolution Unit : inches
X Resolution : 120
Y Resolution : 120
Image Width : 160
Image Height : 120
Encoding Process : Baseline DCT, Huffman coding
Bits Per Sample : 8
Color Components : 3
Y Cb Cr Sub Sampling : YCbCr4:2:2 (2 1)
Image Size : 160x120
Megapixels : 0.019

Thank you!

**Comment by Mohit-Ak** [comment]
I have the same issue. Did you manage to solve it?
```

~/.local/lib/python3.6/site-packages/flirimageextractor/flirimageextractor.py in process_image(self, flir_img_file, RGB)
     99 
    100         # if its a TIFF different settings are required
--> 101         if self.get_image_type().upper().strip() == "TIFF":
    102             # valid for tiff images from Zenmuse XTR
    103             self.use_thumbnail = True

~/.local/lib/python3.6/site-packages/flirimageextractor/flirimageextractor.py in get_image_type(self)
    131             meta_json, err = p.communicate(input=self.flir_img_bytes.read())
    132 
--> 133         return json.loads(meta_json.decode())[0]["RawThermalImageType"]
    134 
    135     def get_rgb_np(self):
```

**Comment by Varat7v2** [comment]
@Mohit-Ak I am using FLIR Lepton 2. This camera does not have radiometry. So I have to try with other way - using directly 14 bit raw data and calibrating it to approximate temperature. `FlirImageExtractor` did not work for me because of my lower functional camera. It depends on which camera you are using.
